#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 17 17:43:45 2019

@author: samchristian
"""
#Performs point-radius method on actual sample
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from astropy.coordinates import SkyCoord
from astropy import units as u
from sklearn.metrics.pairwise import haversine_distances as haversine
import time
start_time = time.time()
data = pd.read_csv(r'/Users/samchristian/Downloads/grb-frompaper.csv')
#change to your filepath
ras = data.loc[:, ['ra']]
decs = data.loc[:, ['dec']]
i = 0
num_in_range = 0
num_in_range2 = 0
num_in_range3 = 0
num_in_range4 = 0
#not part of the point radius method.
#Calculates number of bursts within each sky division
while i < len(ras):
    #decs[i]
    coord = SkyCoord(ra=ras.iloc[i], dec=decs.iloc[i], unit=(u.deg, u.deg))
    b = coord.galactic.b.deg
    if ((b < 20 and b > -20) and (decs.iloc[i].values > 45 or decs.iloc[i].values < -45)):
        num_in_range += 1
    if (not(b < 20 and b > -20) and (decs.iloc[i].values > 45 or decs.iloc[i].values < -45)):
        num_in_range2 += 1
    if (not(b < 20 and b > -20) and not(decs.iloc[i].values > 45 or decs.iloc[i].values < -45)):
        num_in_range3 += 1
    if ((b < 20 and b > -20) and not(decs.iloc[i].values > 45 or decs.iloc[i].values < -45)):
        num_in_range4 += 1        
    i += 1
print(num_in_range)
print(num_in_range2)
print(num_in_range3)
print(num_in_range4)
data = data.loc[(data['z'] <= 2.1) & (data['z'] >= 1.6)] #upper bound comes first!. Removed zs1
ras11 = data.loc[:, ['ra']]
decs11 = data.loc[:, ['dec']]
DFoutput = pd.concat([ras11, decs11], axis = 1)
DFoutput.to_csv('/Users/samchristian/Downloads/grb-doublecheck1.csv')
ras_inrange = []
decs_inrange = []
def random_point_on_sky():
    dec = np.arcsin(np.random.random(1)*2-1)
    RA = np.random.random(1)*2*np.pi
    return [RA*180/np.pi, dec*180/np.pi]
#returns in degrees
def print_random_star_coords(nstars):
    dec = np.arcsin(np.random.random(1)*2-1)
    RA = np.random.random(1)*2*np.pi
    return [dec[0], RA[0]]
#returns in radians
i = 0
ras1 = []
decs1 = []
print(len(ras11))
while i < len(ras11):
    ras1.append(ras11.iloc[i])
    decs1.append(decs11.iloc[i])
    i += 1
test_radii = 10000
i = 0
radius = 0.8953539
num_in_distance = []
max_coords = []
while i < test_radii:
    in_distance = []
    test_point = print_random_star_coords(1)
    max_coords.append(test_point)
    j = 0
    while j < len(ras1):
        distance = haversine([test_point, [decs1[j]*np.pi/180, ras1[j]*np.pi/180]])
        if distance[0][1] < radius:
            in_distance.append(1)
        j += 1
    num_in_distance.append(len(in_distance))
    i += 1
print(max(num_in_distance))
max_coord_index = num_in_distance.index(max(num_in_distance))
max_coord = max_coords[max_coord_index]
print(max_coord)
i = 0
coords_in_radius = []
#This section is to find the bursts located within the optimal circle
#It is used to generate the demonstrate the location of the HCB
while i < len(ras1):
    distance = haversine([max_coord, [decs1[i]*np.pi/180, ras1[i]*np.pi/180]])
    if distance[0][1] < radius:
        coords_in_radius.append([ras1[i].values[0], decs1[i].values[0]])
    i += 1
print(coords_in_radius)
outputradius = pd.DataFrame.from_records(coords_in_radius)        
print("--- %s seconds ---" % (time.time() - start_time))
#Change to custom filepath
outputradius.to_csv('/Users/samchristian/Downloads/grb-outputinradius1.csv')
